### ISSUE TITLE
There is no ontology for the indexing namespace

### ISSUE THREAD

**Issue by acoburn** [fcrepo4/ontology#12]
The indexing namespace is defined in [org.fcrepo.kernel.RdfLexicon](https://github.com/fcrepo4/fcrepo4/blob/master/fcrepo-kernel/src/main/java/org/fcrepo/kernel/RdfLexicon.java#L101) and used throughout the fcrepo-message-consumer. It is also referenced in various places in the [documentation](https://wiki.duraspace.org/display/FEDORA40/External+Search#ExternalSearch-Markaresourceasindexableandassignanappropriateindexingtransformation), but the URI doesn't actually refer to any RDFS or OWL ontology. 

For instance, this link: http://fedora.info/definitions/v4/indexing returns a 404 Not Found error. Would it make sense to create an ontology for these predicates:

    indexing:indexable
    indexing:hasIndexingTransform

Or would it be better to add them to the existing `repository` ontology? Either way, I think it is a good idea to back the namespace with some type of  RDFS/OWL representation. And are there other predicates that make use of this namespace?

**Comment by awoods** [comment]
The indexing# namespace, as well as config# and [authorization#](https://github.com/fcrepo4/fcrepo-module-auth-rbacl/blob/master/fcrepo-auth-roles-common/src/main/resources/cnd/access-control.cnd#L4) namespaces have been viewed as either experimental or inward-facing. I am inclined to hold off on config# (it is useful for experimental predicates) and authorization# (this may change very soon in the light of Web Access Control), but indexing# could reasonably fold into `repository#`.
I would be interested to hear what others think.

**Comment by escowles** [comment]
I agree that the indexing triples would be a good fit for the repository ontology -- but don't we have code that prevents updating properties in the repository ontology?

**Comment by ajs6f** [comment]
-1 to putting the indexing predicates in the repository ontology. What goes in the repository ontology should be exactly those types and relationships that construct a repository. The indexing predicates do no such thing. In fact, stripping them wholesale from a repo in which they appear wouldn't be particularly noticeable from a Linked Data point of view. 

+1 to putting them into a formal publication, but that should be in their own namespace.

**Comment by awoods** [comment]
Indeed, @escowles: https://github.com/fcrepo4/fcrepo4/blob/master/fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/rdf/JcrRdfTools.java#L260

So the question becomes, for server-aware user-mutable properties, do we want to invent Fedora-specific namespaces, or use existing ones? If we tend towards the former, then we should likely publish a new namespace.

**Comment by ajs6f** [comment]
There is no generic answer to that question. In every case we must ask: with what functions and models do these properties concern themselves?

**Comment by awoods** [comment]
Let's start with the examples of #indexable and #hasIndexingTransform. I have not looked, but it seems unlikely that we will find analogous predicates in the wild, particularly for #hasIndexingTransform. If we do define and publish a set Fedora-aware user-mutable predicates, I would prefer that they reside within a single namespace. That would leave the Fedora project with two published namespaces: `repository#` and `somethingelse#`. `config#` seems potentially reasonable for a namespace of user-mutable predicates.
Thoughts?

**Comment by escowles** [comment]
:+1: to `config#` -- that seems like a good name for this (and potentially other) user-configurable properties where there isn't a good existing ontology to use.

**Comment by awoods** [comment]
Tracking with: https://jira.duraspace.org/browse/FCREPO-1285
