### ISSUE TITLE
Repository namespace

### ISSUE THREAD

**Issue by acoburn** [fcrepo4/ontology#14]
@ajs6f mentioned wanting a clean repository namespace document. When I looked through the fedora repository.rdf document, there are a few items I'm wondering about.

  * Classes standardly are capitalized. There are three `owl:Class` definitions that are not capitalized
        * [repository:configuration](https://github.com/fcrepo4/ontology/blob/master/repository.rdf#L665) (used by the fcrepo-transform module) 
        * [repository:nodeTypeConfiguration](https://github.com/fcrepo4/ontology/blob/master/repository.rdf#L724) (used by the fcrepo-transform module) 
        * [repository:relations](https://github.com/fcrepo4/ontology/blob/master/repository.rdf#L754) (didn't see any use of this in the codebase) 

    Should these be capitalized?

  * There are a lot of properties with dot.notation https://github.com/fcrepo4/ontology/blame/master/repository.rdf#L310

    Is this the best format for properties? I have usually seen these in camelCase. I also didn't see any use of these properties in the fcrepo4 codebase.

  * The `isDeep` property lists `repository:Lock` as its domain, but there is no `repository:Lock` class. https://github.com/fcrepo4/ontology/blob/master/repository.rdf#L201

**Comment by escowles** [comment]
@acoburn: I'm fine with updating the classes to all be capitalized, and removing the isDeep property now that locks have been removed.

For the repository.* properties, these are generated from Modeshape configuration property names (see https://github.com/fcrepo4/fcrepo4/blob/master/fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/rdf/impl/RootRdfContext.java#L90).  There was a Pivotal ticket to make these camelCase, but I don't see a JIRA ticket for that.  So we should make sure we update the generation of those triples when we update the ontology.

**Comment by awoods** [comment]
@escowles, I am not seeing the Pivotal ticket that you reference.
https://www.pivotaltracker.com/n/projects/684825

In any case, let's clean up the ontology and related usages in the code.

**Comment by escowles** [comment]
@awoods I think the ticket I was thinking of is:

https://www.pivotaltracker.com/n/projects/684825/stories/75047684

Changing the names to camelCase was the second item, but we didn't actually do that (I thought we made a separate ticket for that, but I don't see it).  Agreed that we should clean up the ontology, including updating the format of the repository config predicates to camelCase.

**Comment by acoburn** [comment]
@escowles what do you think about removing the repository:hasLockToken property?

**Comment by escowles** [comment]
@acoburn Since we've removed locking from the REST API, I definitely think we should remove the hasLockToken property.

**Comment by awoods** [comment]
:+1: to dropping the lock property.

**Comment by awoods** [comment]
Tracking with: https://jira.duraspace.org/browse/FCREPO-1309
