### ISSUE TITLE
The HTML view of these ontologies is pretty bland

### ISSUE THREAD

**Issue by acoburn** [fcrepo4/ontology#19]
What would you all think of adding a bit more style to the HTML view of the ontologies? This would not change their content at all (no a new release would not be necessary), but rather would involve adjusting the various XSLT so that the resulting HTML was a bit prettier.

**Comment by escowles** [comment]
:+1:  -- the HTML is very utilitarian and making it look nicer sounds like a good idea to me.

**Comment by ajs6f** [comment]
+1

**Comment by awoods** [comment]
Pretty is nice... if you have the time and interest :nail_care:

**Comment by acoburn** [comment]
I can fit it in at some point over the next few weeks. I've added a JIRA ticket for this: https://jira.duraspace.org/browse/FCREPO-1359
